### ISSUE TITLE
Titanic - Getting ZeroDivisionError when I try to do network.bake()

### ISSUE THREAD

**Issue by yeskarthik** [ronojoy/pylearn#1]
I tried to run the code from master before making any changes and I got 

network.bake()
  File "pomegranate\BayesianNetwork.pyx", line 126, in pomegranate.BayesianNetwork.BayesianNetwork.bake (pomegranate/BayesianNetwork.c:3531)
  File "pomegranate\distributions.pyx", line 2331, in pomegranate.distributions.ConditionalProbabilityTable.joint (pomegranate/distributions.c:38321)
ZeroDivisionError: float division by zero

Also found that both the given probability of survival and perish for third class was 0.0. I thought this was the issue, but giving 1 for one of it didn't solve the problem.

Also, I calculated probabilities from training data and assigned them in the truth table (Hope the approach is right?) You can check my changes here, didn't send a pull request cos its not working yet.
https://github.com/yeskarthik/pylearn/blob/master/scripts/ex4-titanic-disaster.py
But I'm still getting the above error during network.bake() cc: @ronojoy

**Comment by fareez-ahamed** [comment]
@yeskarthik As our previous programs worked fine, I modified them to arrive at this error. It seems something wrong with the package. I have opened an issue in pomegranate repo as well.

https://github.com/jmschrei/pomegranate/issues/13

**Comment by ronojoy** [comment]
@yeskarthik, @fareez-ahamed There is definitely something wrong with the package. I get this error too if I change the state keys. Lets wait for the pomegranate author to respond. In the meantime, lets try to implement the same thing in [pgmpy](https://github.com/pgmpy/pgmpy) ?

**Comment by yeskarthik** [comment]
Couldn't use pgmpy cos it requires python3! And thanks to @jmschrei pomegranate issue is now fixed. :+1: closing this now.
